# Generated by Django 5.0.3 on 2024-03-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
