# Generated by Django 5.0.3 on 2024-03-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoms", "0002_customer_address_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiondetail",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
