# Generated by Django 5.0.3 on 2024-03-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0002_customer_address'),
        ('ecoms', '0002_customer_address_product_description_and_more'),
    ]

    operations = [
    ]
