# Generated by Django 5.0.3 on 2024-03-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0003_alter_transactiondetail_qty'),
        ('ecoms', '0003_merge_20240326_1651'),
    ]

    operations = [
    ]
