# Generated by Django 5.0.3 on 2024-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0005_alter_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
