# Generated by Django 4.2.9 on 2024-06-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0005_alter_cart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Customer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecoms.customer')),
                ('bank_account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            bases=('ecoms.customer',),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6),
        ),
    ]
