# Generated by Django 5.0.3 on 2024-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0006_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='subdistrict',
            field=models.CharField(default='', max_length=30),
        ),
    ]
