# Generated by Django 4.2.9 on 2024-06-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0006_bank_customer_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[{'Female': 'female', 'Male': 'male'}], default='Male', max_length=6),
        ),
        migrations.DeleteModel(
            name='Bank_Customer',
        ),
    ]
