# Generated by Django 5.0.3 on 2024-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0007_customer_city_customer_picture_customer_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
