# Generated by Django 4.2.9 on 2024-06-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0007_alter_customer_gender_delete_bank_customer'),
        ('ecoms', '0009_alter_cart_qty'),
    ]

    operations = [
    ]
