# Generated by Django 5.0.3 on 2024-06-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0012_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
