# Generated by Django 5.0.3 on 2024-06-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0007_alter_customer_gender_delete_bank_customer'),
        ('ecoms', '0013_alter_product_product_image'),
    ]

    operations = [
    ]
