# Generated by Django 3.2.6 on 2024-06-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0010_merge_20240613_1327'),
        ('ecoms', '0013_alter_product_product_image'),
    ]

    operations = [
    ]
