# Generated by Django 5.0.3 on 2024-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0014_merge_20240616_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Female')], default='Male', max_length=6),
        ),
    ]
