# Generated by Django 5.0.3 on 2024-06-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0014_merge_20240613_1439'),
        ('ecoms', '0015_alter_customer_gender'),
    ]

    operations = [
    ]
