# Generated by Django 5.0.3 on 2024-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0016_merge_20240620_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=1),
        ),
    ]
