# Generated by Django 5.0.3 on 2024-06-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0017_alter_cart_product_id'),
        ('seller', '0005_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
