# Generated by Django 5.0.3 on 2024-06-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0019_alter_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='product_id',
            field=models.IntegerField(default=''),
        ),
    ]
