# Generated by Django 3.2.6 on 2024-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0014_merge_20240622_0742'),
        ('ecoms', '0019_alter_cart_product_id'),
    ]

    operations = [
    ]
