# Generated by Django 3.2.6 on 2024-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0020_merge_20240623_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[{'Female': 'female', 'Male': 'male'}], default='Male', max_length=6),
        ),
    ]
