# Generated by Django 5.0.3 on 2024-06-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0020_alter_transactiondetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
