# Generated by Django 3.2.6 on 2024-06-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0020_alter_customer_gender'),
        ('ecoms', '0021_alter_transactiondetail_product_id'),
    ]

    operations = [
    ]
