# Generated by Django 3.2.6 on 2024-06-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoms', '0021_alter_transactiondetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[{'Female': 'female', 'Male': 'male'}], default='Male', max_length=6),
        ),
    ]
