# Generated by Django 5.0.3 on 2024-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
        migrations.AddField(
            model_name='delivery',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
