# Generated by Django 5.0.3 on 2024-06-24 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_telp", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=200)),
                ("no_rek", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_description", models.CharField(max_length=100)),
                (
                    "product_category",
                    models.CharField(default="lainnya", max_length=100),
                ),
                ("product_price", models.IntegerField()),
                ("stock_gudang", models.IntegerField()),
                (
                    "product_image",
                    models.ImageField(
                        default="default_product.jpg", upload_to="product_images"
                    ),
                ),
                ("supplier", models.CharField(default="none", max_length=100)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.seller"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("total_price", models.IntegerField()),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.product"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.seller"
                    ),
                ),
            ],
        ),
    ]
