# Generated by Django 5.0.3 on 2024-06-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
