# Generated by Django 4.2.9 on 2024-06-12 08:53

import bank.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ktp_photo', models.ImageField(blank=True, null=True, upload_to=bank.models.upload_to)),
            ],
        ),
    ]
