# Generated by Django 4.2.9 on 2024-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_bankaccount_id_alter_bankaccount_bank_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
