# Generated by Django 4.2.9 on 2024-06-12 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_active',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
            ],
        ),
    ]
