# Generated by Django 4.2.9 on 2024-06-12 17:37

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_bankaccount_is_active_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='application',
            name='ktp_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bank.models.upload_to),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
