# Generated by Django 3.2.6 on 2024-06-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_transactionhistory_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('P', 'Purchase')], max_length=1),
        ),
    ]
