# Generated by Django 3.2.6 on 2024-06-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_remove_topuphistory_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined')], default='P', max_length=1),
        ),
    ]
