# Generated by Django 3.2.6 on 2024-06-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_application_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopUpHistory',
        ),
    ]
