# Generated by Django 3.2.6 on 2024-06-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0012_delete_topuphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bankadmin',
            name='username',
        ),
        migrations.AddField(
            model_name='bankadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
