# Generated by Django 5.0.6 on 2024-06-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_product_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(default=12312),
            preserve_default=False,
        ),
    ]
