# Generated by Django 5.0.6 on 2024-06-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0003_product_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(max_length=100),
        ),
    ]
