# Generated by Django 5.0.6 on 2024-06-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0006_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="supplier.product",
            ),
        ),
    ]
