# Generated by Django 3.2.6 on 2024-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_sellerbuyrequest'),
        ('supplier', '0007_product_product_thumbnail_alter_productimage_product'),
    ]

    operations = [
    ]
